# ==========================================================
# Basic Information 
# ==========================================================
title: Wenbo (Vito) Zhu
position: Founding AI Lead
affiliation: OpusClip, UC Berkeley
email: wenbo_zhu@berkeley.edu

# ==========================================================
# Search Engine Optimization (SEO)
# ==========================================================
keywords: Wenbo Zhu, Vito Zhu, OpusClip, UC Berkeley Alumni, Generative Video, Multimodal, LLM Agent, CVPR, ACL, AAAI, NeurIPS
description: Founding AI Lead at OpusClip. Master of Engineering at Berkeley.Specializing in multimodal video understanding, generative video editing, and agentic systems.
canonical: https://vitozhu04.github.io/

# ==========================================================
# Links 
# ==========================================================
google_scholar: https://scholar.google.com/citations?user=z_4-QfQAAAAJ
cv_link: assets/files/resume.pdf
github_link: https://github.com/vitozhu04
linkedin: https://www.linkedin.com/in/wenbo-zhu-9138a5125

# ==========================================================
# Images 
# ==========================================================
avatar: ./assets/img/profile.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# ==========================================================
# Footnote
# ==========================================================
enable_footnote: true

# ==========================================================
# Auto Dark Mode
# ==========================================================
auto_dark_mode: true

# ==========================================================
# Font
# ==========================================================
font: "Sans Serif"  # 更现代，适合科技/AI类网站

# ==========================================================
# Google Analytics ID
# ==========================================================
# 如果你想统计访问流量，替换成自己的 ID
# google_analytics: G-XXXXXXXXXX

# ==========================================================
# Remote Theme
# ==========================================================
remote_theme: yaoyao-liu/minimal-light

# ==========================================================
# Excluded Files
# ==========================================================
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
